version: '3'
services:
  crtl-prototype-studios-website-strapicms:
    container_name: crtl-prototype-studios-website-strapicms
    build: .
    image: crtl-prototype-studios-website-strapicms:latest
    restart: unless-stopped
    env_file: .env
    environment:
      DATABASE_CLIENT: ${DATABASE_CLIENT}
      DATABASE_HOST: crtl-prototype-studios-website-strapicmsDB
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PORT: ${DATABASE_PORT}
      JWT_SECRET: ${JWT_SECRET}
      ADMIN_JWT_SECRET: ${ADMIN_JWT_SECRET}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      NODE_ENV: ${NODE_ENV}
    volumes:
      - ./config:/opt/app/config
      - ./src:/opt/app/src
      - ./package.json:/opt/package.json
      - ./package-lock.json:/opt/package-lock.json

      - ./.env:/opt/app/.env
      - ./public/uploads:/opt/app/public/uploads
    ports:
      - '1337:1337'
    networks:
      - crtl-prototype-studios-website-strapicms
    depends_on:
      - crtl-prototype-studios-website-strapicmsDB
      
  crtl-prototype-studios-website-strapicmsDB:
    container_name: crtl-prototype-studios-website-strapicmsDB
    platform: linux/amd64 #for platform error on Apple M1 chips
    restart: unless-stopped
    env_file: .env
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_USER: ${DATABASE_USERNAME}
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_ROOT_HOST: '%'
    volumes:
      - crtl-prototype-studios-website-strapicms-data:/var/lib/mysql
      #- ./data:/var/lib/postgresql/data/ # if you want to use a bind folder
    ports:
      - '10005:10005'
    networks:
      - crtl-prototype-studios-website-strapicms
      
  crtl-prototype-studios-website-strapicmsAdminer:
    container_name: crtl-prototype-studios-website-strapicmsAdminer
    image: adminer
    restart: unless-stopped
    ports:
      - '9090:8080'
    environment:
      - ADMINER_DEFAULT_SERVER=crtl-prototype-studios-website-strapicmsDB
    networks:
      - crtl-prototype-studios-website-strapicms
    depends_on:
      - crtl-prototype-studios-website-strapicmsDB

volumes:
  crtl-prototype-studios-website-strapicms-data:

networks:
  crtl-prototype-studios-website-strapicms:
    name: Crtl-prototype-studios-website-strapicms
    driver: bridge
