// Interface automatically generated by schemas-to-ts

import { Media } from '../../../../common/schemas-to-ts/Media';
import { User } from '../../../../common/schemas-to-ts/User';
import { User_Plain } from '../../../../common/schemas-to-ts/User';
import { AdminPanelRelationPropertyModification } from '../../../../common/schemas-to-ts/AdminPanelRelationPropertyModification';

export enum ProjectStatus {
  Planned = 'Planned',
  Idle = 'Idle',
  Wip = 'WIP',
  Released = 'Released',
  Lts = 'LTS',
  Abandoned = 'Abandoned',}
export enum ProjectType {
  Game = 'Game',
  Software = 'Software',
  Website = 'Website',
  Other = 'Other',}

export interface Project {
  id: number;
  attributes: {
    createdAt: Date;    updatedAt: Date;    publishedAt?: Date;    projectName: string;
    projectDescription: string;
    projectSlug: string;
    projectCover: { data: Media };
    isInEarlyAccess: boolean;
    projectStatus: ProjectStatus;
    projectType: ProjectType;
    projectAuthor?: { data: User };
    locale: string;
    localizations?: { data: Project[] };
  };
}
export interface Project_Plain {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  projectName: string;
  projectDescription: string;
  projectSlug: string;
  projectCover: Media;
  isInEarlyAccess: boolean;
  projectStatus: ProjectStatus;
  projectType: ProjectType;
  projectAuthor?: User_Plain;
  locale: string;
  localizations?: Project[];
}

export interface Project_NoRelations {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  projectName: string;
  projectDescription: string;
  projectSlug: string;
  projectCover: number;
  isInEarlyAccess: boolean;
  projectStatus: ProjectStatus;
  projectType: ProjectType;
  projectAuthor?: number;
  locale: string;
  localizations?: Project[];
}

export interface Project_AdminPanelLifeCycle {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  projectName: string;
  projectDescription: string;
  projectSlug: string;
  projectCover: AdminPanelRelationPropertyModification<Media>;
  isInEarlyAccess: boolean;
  projectStatus: ProjectStatus;
  projectType: ProjectType;
  projectAuthor?: AdminPanelRelationPropertyModification<User_Plain>;
  locale: string;
  localizations?: Project[];
}
