// Interface automatically generated by schemas-to-ts

import { Media } from '../../../../common/schemas-to-ts/Media';
import { AdminPanelRelationPropertyModification } from '../../../../common/schemas-to-ts/AdminPanelRelationPropertyModification';

export interface Post {
  id: number;
  attributes: {
    createdAt: Date;    updatedAt: Date;    publishedAt?: Date;    postTitle: string;
    postSlug: string;
    postCover: { data: Media };
    postContent: string;
    locale: string;
    localizations?: { data: Post[] };
  };
}
export interface Post_Plain {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  postTitle: string;
  postSlug: string;
  postCover: Media;
  postContent: string;
  locale: string;
  localizations?: Post[];
}

export interface Post_NoRelations {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  postTitle: string;
  postSlug: string;
  postCover: number;
  postContent: string;
  locale: string;
  localizations?: Post[];
}

export interface Post_AdminPanelLifeCycle {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  postTitle: string;
  postSlug: string;
  postCover: AdminPanelRelationPropertyModification<Media>;
  postContent: string;
  locale: string;
  localizations?: Post[];
}
